### ISSUE TITLE
Exception documentation

### ISSUE THREAD

**Issue by KampfCaspar** [peej/phpdoctor#10]
@exception/@throws should be synonymous

@throws AException  if condition b is met
is translated to
<a>if condition b is met</a>
whereas
<a>AException</a> if condition b is met
seems more appropriate ;)

**Comment by peej** [comment]
PHPDoctor does not define a @exception tag and thus uses the default taglet to display the tag. Unless there is lots of code out in the wild using @exception, we should encourage people to use the @throws tag.

If someone needs the tag for their specific code, they can easily add a custom taglet to handle it.

A quick look at phpdocumentor shows that it doesn't implement either tag.

**Comment by KampfCaspar** [comment]
There probably is a misunderstanding about the second point:
phpdoctor does support @throws, but swallows the first word (Exception class name) if more text is given. This contradicts the spec at
http://java.sun.com/j2se/1.5.0/docs/tooldocs/windows/javadoc.html#@throws

As code says more than human words, please accept the following diff as suggestion:

<pre><code>
diff --git a/classes/throwsTag.php b/classes/throwsTag.php
index be86551..5f82658 100644
--- a/classes/throwsTag.php
+++ b/classes/throwsTag.php
@@ -51,7 +51,30 @@ class ThrowsTag extends SeeTag
     {
                return 'Throws';
        }
-       
+
+       /** Get value of this tag.
+        *
+        * @return str
+        */
+       function text()
+    {
+               $link = $this->_link;
+               $res = '';
+
+               $element =& $this->_resolveLink();
+               if ($element && $this->_parent) {
+                       $package =& $this->_parent->containingPackage();
+                       $path = str_repeat('../', $package->depth() + 1).$elemen
+                       $res = '<a href="'.$path.'">'.$link.'</a>';
+               } elseif (preg_match('/^(https?|ftp):\/\//', $this->_link) === 1
+                       $res = '<a href="'.$this->_link.'">'.$link.'</a>';
+               } else {
+                       $res =  $link;
+               }
+
+               return $res . ($this->_text ? ' ' . $this->_text : '');
+       }
+
        /** Return true if this Taglet is used in constructor documentation.
      *
      * @return bool
@@ -70,7 +93,7 @@ class ThrowsTag extends SeeTag
                return FALSE;
        }
 
-       /** Return true if this Taglet is used in method documentation.         
+       /** Return true if this Taglet is used in method documentation.
      *
      * @return bool
      */
</code></pre>

**Comment by beikov** [comment]
Agree to that patch, but replace the return with the following line to make it prettier:

return '<code>' . $res . '</code>' . ($this->_text ? ' ' . $this->_text : '');

**Comment by peej** [comment]
This patch is in, can someone confirm it now works as expected?

**Comment by beikov** [comment]
It is not working for interfaces!

**Comment by peej** [comment]
This does appear to be working fine for interface methods as well as class methods. I've added a test to make sure.

**Comment by beikov** [comment]
Working for interfaces too, sorry misstyped the name of the class, anyway maybe you could use a code-tag to surround the class name. Would be more like javadoc.
A typical java doc style can be found here http://download.oracle.com/javase/1.4.2/docs/api/java/util/Map.html

it should look like:

Throws:
    ClassCastException - if the key is of an inappropriate type for this map (optional). 
    NullPointerException - if the key is null and this map does not not permit null keys (optional).
