### ISSUE TITLE
enable phpDocumentor style "brief" descriptions

### ISSUE THREAD

**Issue by KampfCaspar** [peej/phpdoctor#11]
In order to "ease" the conversion from the now IMHO defunct phpDocumentor (and attract a lot of additional users ;) ), it would be great if phpDoctor would extend the possible break from brief to full/detailed description:

JavaDoc: First sentence (period plus whitespace)
phpDoctor: first double newline

Could also be limited to the first double newline, if the preceding paragraph does NOT end in punctuation (not strict, but phpDoc documentation does it that way)

For extra karma, this could be configurable ;)

**Comment by peej** [comment]
It should already do this. The code is in tag.php#firstSentenceTags it splits the description on the first period followed by a new line or a HTML tag. If you turn on pearCompat mode it splits on the first two new lines as well as the first period.

Is there a specific docComment that isn't producing the expected results?
