### ISSUE TITLE
index parses html tags

### ISSUE THREAD

**Issue by ghost** [peej/phpdoctor#12]
In CodeIgniter there is a function named set_select which has the following docblock:

```
 /**
  * Set Select
  *
  * Let's you set the selected value of a <select> menu via data in the POST array.
  * If Form Validation is active it retrieves the info from the validation class
  *
  * @access public
  * @param  string
  * @param  string
  * @param  bool
  * @return string
  */
```

When I view the index for my documentation, I can only get to elements that alphabetically precede set_select, because phpdoctor parses that select tag and then stops output. This is all I see:

```
  set_select() - Function in package GiftFlow
     Set Select Let's you set the selected value of a  [[ DISPLAYS SELECT DROPDOWN HERE]]
```

**Comment by peej** [comment]
This appears to be due to the optional parameter name syntax that phpdoc 0.4.1 has and CI uses. I've made some amends to enable this functionality as long as there is no parameter description (as is the case with CI documentation).
