### ISSUE TITLE
Running out of memory

### ISSUE THREAD

**Issue by nathanl** [peej/phpdoctor#16]
On Fedora Linux, I'm trying to run PHPDoctor on a very large code base. It's hitting a fatal error when it runs out of memory at 1GB. This is odd, because I've given it 5GB in php.ini and with an inline set_ini('memory_limit','5120M'), and if I add phpinfo() to the top of phpdoc.php, it claims it has 5120M available. I don't see anything in its own .ini file that sets a limit.

It may turn out that I don't have enough RAM to throw at it to run on our whole code base, but first I want to see what it can do with 5GB. Any ideas?

**Comment by peej** [comment]
No ideas I'm afraid. Does this sound like some kind of limitation of PHP?

**Comment by nathanl** [comment]
Sorry I took so long to respond. I'm not sure if the limit was with PHP or the OS, but I got it to run with 3GB. Someone suggested that setting it to 5 makes it "wrap" back to 1 in a 32-bit environment, but mine should be 64. Anyway, it's working. If you're curious, I asked the question here:

http://stackoverflow.com/questions/3318636/how-else-might-a-php-cli-script-determine-its-memory-limit
