### ISSUE TITLE
support for multiple source folder

### ISSUE THREAD

**Issue by DerManoMann** [peej/phpdoctor#17]
I've got a patch for that based on 05fe88900c9892b3fa81 if you are interested. Doesn't look like I can attach that here?

mano

**Comment by peej** [comment]
If you branch the code, apply your patch and push it to Github, you can send me a pull request. Sounds like a useful patch, thanks.

**Comment by DerManoMann** [comment]
yeah, that would be the proper way I suppose, coming...

**Comment by DerManoMann** [comment]
Hi there,

did you get the pull request?

**Comment by peej** [comment]
Yep, thanks, I haven't had time to pull it yet, will do soon.

**Comment by peej** [comment]
This has been pulled into master. Thanks.
