### ISSUE TITLE
support for {@inheritDoc}

### ISSUE THREAD

**Issue by DerManoMann** [peej/phpdoctor#19]
I think we've discussed this a long time ago, but I can't find the docs any more.
My project uses @inheritDoc quite a lot (which looks not that great in the docs right now), so I think it's time to give that a go again.
From what I can gather the tag is supposed to be replaced by the parent class doc. In addition, there can be new comments/doc beside the @inheritDoc tag.
If yo could give me a few pointers where to start I'd be happy to give that a go

**Comment by peej** [comment]
Hey DerManoMann, I've had a crack at this this afternoon for you. There's a new tag defined in repo in inheritDocTag.php, it should hopefully behave as you expect. I haven't tested it with the standard doclet, only the debug doclet, so let me know how it works for you.

**Comment by DerManoMann** [comment]
cool, thanks, will try  and let you know.

**Comment by DerManoMann** [comment]
oops, did I just close that?
Anyway, things are mostly working - there are two things I can see right now that need be improved:
a) The method summary shows the raw tag while the method details show the correctly inherited contents
b) There seems to be some limitation on the inheritance detection. I have a case where a class extends a base class and implements an interface. The class inheritance is resolved, but the inherited method from the interface (well, the implemented, I guess) is not.

So you could re-open this I guess or I can raise a new issue.

**Comment by peej** [comment]
Thanks for checking this, these issues should now be fixed in the latest commit.

**Comment by DerManoMann** [comment]
Brilliant - thanks a lot. Can't think of anything else I need so good stuff!

Cheers, mano
