### ISSUE TITLE
Include and link annotated source files

### ISSUE THREAD

**Issue by blueyed** [peej/phpdoctor#2]
phpdoctor should include the original source code (optionally) in the output, annotated via e.g. GeSHi.

This would allow to link there from various places, e.g. from the all the places in the class documentation referring to the file.
Of course, this should include anchors for each line and those should get used where appropriate.

**Comment by peej** [comment]
Good idea, I'll look into adding this.

**Comment by peej** [comment]
This has now been added and is in git, if you could give it a try and see how you get on. It's turned on by default, you need to have GeSHi in your PHP path for it to be used, otherewise you don't get pretty printing.
