### ISSUE TITLE
Feature Request for @throws Annotation

### ISSUE THREAD

**Issue by beikov** [peej/phpdoctor#20]
It would be really nice if you could add an throws-clause to the methods docblock. Then it would be more clear where to use a try-catch.

**Comment by beikov** [comment]
adding the following method to the throwsTag.php does the job for me:

/*\* Get value of this tag.
        *
        \* @return str
        */
    function text()
    {
       $link = $this->_link;
       $res = '';

```
   $element =& $this->_resolveLink();
   if ($element && $this->_parent) {
           $package =& $this->_parent->containingPackage();
           $path = str_repeat('../', $package->depth() + 1).($element instanceof ClassDoc ? $element->name(): $element);
           $res = ''.$link.'';
   } elseif (preg_match('/^(https?|ftp):\/\//', $this->_link) === 1){
           $res = ''.$link.'';
   } else {
           $res =  $link;
   }

   return '<code>' . $res . '</code> - ' . ($this->_text ? ' ' . $this->_text : '');
}
```

**Comment by peej** [comment]
This has been applied to master. Thanks.
