### ISSUE TITLE
Create todo list based on @todo tag

### ISSUE THREAD

**Issue by roland-d** [peej/phpdoctor#21]
Hello,

I also have come from PhpDocumentor and I like to use the @todo tag in my code for reminding myself what to do. In PhpDocumentor this creates a single todo page but phpdoctor doesn't seem to support it yet. I would think to create an HTML file like readme.html that would show up under the All Items link will be perfect.

Thanks.

**Comment by beikov** [comment]
That is a really nice feature, Doxygen has is too but it has not such a good PHP support like PHPdoctor

**Comment by peej** [comment]
I've added a todo writer to the standard doclet. It's basically a clone of the deprecated writer but picking up the @todo tag instead.

**Comment by roland-d** [comment]
@peej, that is good news. Thanks for that.

**Comment by AriMcBrown** [comment]
I love the @todo tag, but it doesn't show the string I feed it. I've also noticed the TODO link is not available in the following pages:
- Overview
- Files
- Package (Instead it shows Index twice)

Hope it's useful

**Comment by peej** [comment]
Thanks McBrown, I've updated the standard doclet to include these todo tag fixes. You should find this fix in 1ef0c513051d7382f2e74a7d3c214ea79ac461ad.

**Comment by beikov** [comment]
For me it works properly, really nice feature!

**Comment by AriMcBrown** [comment]
It works great now!
