### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by beikov** [peej/phpdoctor#22]
Here is a short list of features I am missing in phpdoctor:
- General: Allow source path to be relative to the ini path
- General: Allow @access to overwrite the given modifier -> check if $currentData['access'] is already set(~near at line 655)
- Class Doc: Show all implemented interfaces
- Class Doc: Show direct known subclasses
- Class Doc: Link to the class in the "Methods inherited from class ..."-table
- Interface Doc: Show all known implementing classes
- Interface Doc: All known subinterfaces
- Interface Doc: All superinterfaces

**Comment by DerManoMann** [comment]
+1 great, just the list of things I was about to raise!
(except for the #1 and #2, perhaps. is there any real use case for #1 where the same could not be archived differently?)

**Comment by beikov** [comment]
#1: really useful if documentation is made on different OSs
#2: there are no inner classes in PHP and some of the implementations should not be documented e.g. custom iterator for a collection because the iterator just implements the interface for the specific collection

For concrete use cases look at my project: http://sourceforge.net/projects/blazeframework/

In files like src/blaze/collections/maps/HashMap I need a custom iterator and this class should not be documented.

**Comment by beikov** [comment]
There is also a need for the following things:
- Linking to the classes when multiple types are allowed for return/param values e.g. blaze\lang\String|blaze\lang\ClassWrapper|string
- Allowing the following syntax for type documentation: array[blaze\lang\String] and blaze\collections\ListI[blaze\lang\String] and for maps blaze\collections\Map[blaze\lang\String, blaze\lang\Object] with linking to the classes.
- Do not document Packages/Classes/Methods/Fields which have annotation @access private if not specified in configuration
- Make own table for constructor documentation and make a @constructor-annotation which can be specified on e.g. private methods for special documentation. This is important if you have optional parameters and want to have specialized documentation for the constructors with different params. A standard implementation for this could look like:

public function __construct($bla = null, $blub = null){
   if($blub === null){
      if($bla === null){
         $this->construct0();
      }else{
         $this->construct1($bla);
      }
   }else{
       $this->construct3($bla, $blub);
   }
}

/**
- @constructor
  _/
  private function construct0(){}
  /_*
- @constructor
  _/
  private function construct1($bla){}
  /_*
- @constructor
  */
  private function construct2($bla, $blub){}

Maybe this could be made for normal methods too if someone would need that.

**Comment by beikov** [comment]
In addition to @throws: The displayed name of the exception class should be shortened-> \main\sub\package1\TestException will be displayed as TestException

Same thing for @see and @link
