### ISSUE TITLE
Create PEAR package

### ISSUE THREAD

**Issue by mtdowling** [peej/phpdoctor#23]
PHPDoctor needs a PEAR package for easy installation.  I think this would help the adoption of PHPDoctor.

**Comment by peej** [comment]
Do you have any idea how to make a PEAR package, I have never really used PEAR?

**Comment by shupp** [comment]
I can help with this if you want.

Cheers,

Bill

**Comment by peej** [comment]
That'd be great Bill.

I haven't had the time to look into how PEAR works etc. If you know how it all works and can help me get started please do.
