### ISSUE TITLE
Access html of source files via HTTP is broken

### ISSUE THREAD

**Issue by vdmeer** [peej/phpdoctor#24]
Verion: 2 RC4
OS: Windows 7
Problem: using Apache, the link to source files is broken because parts of the filename contain backslash '\' character, rather than forwardslash '/'.

I am using the standard doclet, so two patches helped me as a workaround:
sourceWriter.php, line 62, add an str_replace: str_replace("\", "/", strtolower($filename))
htmlWrite.php, line 195, add an sre_replace: str_replace("\", "/", strtolower($doc->sourceFilename()))

I am not sure if that's a bug or a feature (for HTTP access to generated API doc it's a bug)...
thanks
Sven

**Comment by peej** [comment]
Thanks for this path. I have added this into the repo.
