### ISSUE TITLE
relative filename truncated using multiple source folder

### ISSUE THREAD

**Issue by DerManoMann** [peej/phpdoctor#25]
When using multiple source folder the relative filename displayed is sometimes too short or too long, depending on the length difference of the various source folders configured.
[I guess that perhaps I should be fixing fix ;)]

**Comment by DerManoMann** [comment]
Ah, when I added the code for multiple source folder I didn't take into account that calls to getSourcePath might happen much later than when the files are processed.
It seems it is used only after all parsing is done, so the converting to a relative path is always done using the last source folder path.
I think it would be a lot cleaner to add another sourcePath c'tor parameter after lineNumber to cover for that.
I'll have a go at that if that is ok

**Comment by DerManoMann** [comment]
pull requested - seems to work fine for me now

**Comment by peej** [comment]
Thanks for this, fix pulled.
