### ISSUE TITLE
more of a question: code formatting

### ISSUE THREAD

**Issue by DerManoMann** [peej/phpdoctor#29]
Hi there,
I've tried various ways of formatting code examples (<pre>, <code>), but none seem to be working really well.
<pre>seems to be somewhat ok, however lines seem to be getting trimmed somewhere, so indentation gets lost.
is there a recommended way or would that be a new feature?

**Comment by peej** [comment]
Michael-h is looking into wiring in formatters for docblocks in issue #33 have a look and see if there's anything you can add.
