### ISSUE TITLE
Notice: undefined property PHPDoctor::$_pearCompat

### ISSUE THREAD

**Issue by blueyed** [peej/phpdoctor#3]
With current Git I'm getting a lot of the following notices:

[...]
Writing "source/blogs/htsrv/async.php.html"
PHP Fatal error:  Call to a member function containingPackage() on a non-object in /path/to/phpdoctor/classes/seeTag.php on line 79
PHP Stack trace:
PHP   1. {main}() /path/to/phpdoctor/phpdoc.php:0
PHP   2. PHPDoctor->execute() /path/to/phpdoctor/phpdoc.php:53
PHP   3. Standard->standard() /path/to/phpdoctor/classes/phpDoctor.php:1040
PHP   4. SourceWriter->sourceWriter() /path/to/phpdoctor/doclets/standard/standard.php:179
PHP   5. HTMLWriter->_processInlineTags() /path/to/phpdoctor/doclets/standard/sourceWriter.php:100
PHP   6. LinkTag->text() /path/to/phpdoctor/doclets/standard/htmlWriter.php:298
PHP   7. SeeTag->text() /path/to/phpdoctor/classes/linkTag.php:49

**Comment by peej** [comment]
I removed the _pearCompat option as it was redundant. Is this problem still occurring for you, the stack trace in your comment appears to be for the missing package issue?

**Comment by nijel** [comment]
I can see this in current Git:

PHP Notice:  Undefined property: PHPDoctor::$_pearCompat in /tmp/phpdoctor/classes/phpDoctor.php on line 482

**Comment by peej** [comment]
I can not recreate this issue. The pearCompat option is totally removed from the sourcecode, can you make sure you are up to date. It could be something to do with the value being set in your config file maybe?

**Comment by nijel** [comment]
It does not seem to be completely removed:
    $ git grep pearCompat
    classes/tag.php:                if ($phpdoctor->getOption('pearCompat')) {

**Comment by peej** [comment]
Not sure how I missed that. For some reason my search didn't find it.

I've brought back the pearCompat option since it now appears still to be needed.

Thanks Nijel.
