### ISSUE TITLE
Fatal error: Call to a member function containingPackage() on a non-object

### ISSUE THREAD

**Issue by blueyed** [peej/phpdoctor#4]
Current Git (a620a895cd58a896991becb6b460af264d94e8b6) fails with the following fatal error:
PHP Fatal error:  Call to a member function containingPackage() on a non-object in /path/to/phpdoctor/classes/seeTag.php on line 79
PHP Stack trace:
PHP   1. {main}() /path/to/phpdoctor/phpdoc.php:0
PHP   2. PHPDoctor->execute() /path/to/phpdoctor/phpdoc.php:53
PHP   3. Standard->standard() /path/to/phpdoctor/classes/phpDoctor.php:1033
PHP   4. SourceWriter->sourceWriter() /path/to/phpdoctor/doclets/standard/standard.php:179
PHP   5. HTMLWriter->_processInlineTags() /path/to/phpdoctor/doclets/standard/sourceWriter.php:100
PHP   6. LinkTag->text() /path/to/phpdoctor/doclets/standard/htmlWriter.php:298
PHP   7. SeeTag->text() /path/to/phpdoctor/classes/linkTag.php:49

**Comment by peej** [comment]
Fixed
