### ISSUE TITLE
Treat __construct as Constructor

### ISSUE THREAD

**Issue by gossi** [peej/phpdoctor#42]
Hey there,

I use the magic php __construct method for my constructors. So, they are treated as methods. In my Index I have a bunch of __constrcut methods for each constructor I have.  Could you change that please?

Thanks

**Comment by peej** [comment]
Is the best solution to simply not output the constructor objects in the index?

**Comment by gossi** [comment]
Hey peej,

yes, that makes sense to me.
I checked back my generated docs and on the class pages __construct isn't treated as contructor there, too. Would love to have it there :)

Thanks

**Comment by peej** [comment]
Yeh, originally the constructor had it's own section like Javadoc, but since a class can only have one constructor in PHP, this was changed to place it in with the regular methods. I think this makes more sense esp. since it always appears at the top of the methods list.

**Comment by peej** [comment]
This has now been done in commit 9d34f4be28f0eec42952f0c5150ea9d291f60c0d

**Comment by gossi** [comment]
Actually constructor and methods are two different use cases for me. Where methods more like optional, a constructor is a must for classes. This is why I think it deserves its own section. I think this would increase the usability for people reading the docs.
