### ISSUE TITLE
underscore as 1st char in methods name

### ISSUE THREAD

**Issue by sbnet** [peej/phpdoctor#48]
It seems that methods that have an underscore as the 1st character of its name doesn't appear in the generated doc.

I used tho named some of my methods like that : 

public function _redirect_to($destination)
{
}

but phpdoctor doesn't generate the documentation for them.

Is it a bug or am I missing something ?

Regards,
Steph.

**Comment by peej** [comment]
Hi Steph,

PHPDoctor follows the old PHP4 practice of treating methods and member
variables that start with an underscore as private, and by default it
does not document private members. You can turn on documentation
private members in the config and your _redirect_to() method should
then show up.

Paul.

On 29 June 2011 15:36, sbnet
reply@reply.github.com
wrote:

**Comment by sbnet** [comment]
Thanks, it works perfectly with the option to display also private methods.
