### ISSUE TITLE
Wrong stripping of @package

### ISSUE THREAD

**Issue by nijel** [peej/phpdoctor#5]
The @package tag should IMHO consume just one line and not follow to next lines.

Sample:

```
/**
* @package JAMA
* 
* Error handling
* @author Michael Bommarito
* @version 01292005
*/
```

This should create package JAMA with file comment Error handling.

**Comment by nijel** [comment]
This is quite related with issue #1.

**Comment by peej** [comment]
The code is based on Javadoc and thus expects all tags to appear after the textual content of the doccomment. If you want to place all items in a file into a certain package, then the new file level comment functionality will do the trick. This works as per phpdocumentor, see issue #1.

**Comment by nijel** [comment]
Isn't there chance to make @package tag consume just one line?

**Comment by peej** [comment]
Is there an example of code in the wild that goes against the Javadoc recommendation and puts the package tag before the textual content?

Changing the behaviour would require making a special case for the package tag and I'm not a fan of special cases.

**Comment by nijel** [comment]
The example I've shown is from http://phpexcel.codeplex.com/

**Comment by nathanl** [comment]
peej - I think I've got the same problem. We have a file that contains something like this:
- @package Supplemental
- Copyright 2004 Firstname Lastname
- http://www.example.com.....

And PHPDoctor fails trying to create a directory named "Supplemental Copyright 2004 Firstname Lastname http://www.example.com..."

So the fix, then, is to conform to standards and put the "@package" after all the comments?

**Comment by nathanl** [comment]
Answered my own question - yes, that does fix it. :) I'm new to generating documentation, so I didn't know that the ordering mattered. Maybe a cautionary note here would help others? http://peej.github.com/phpdoctor/more.html#doc-comments

**Comment by peej** [comment]
Since tags can spread over multiple lines within a doccomment, it's not possible to place them before the doccomment description since it would then not be possible to tell if the description was actually part of the tag or not.

I've updated the doccomments section of the website with a link to the Javadoc usage guide on Sun's website.
