### ISSUE TITLE
phpDoctor->makeAbsolutePath mangles any path containing a directory ending in '.'

### ISSUE THREAD

**Issue by NuclearDog** [peej/phpdoctor#54]
My code repository is located at:

/usr/local/www/domain.com/subdomain./htdocs/mycode/

The issue occurs in that when phpDoctor attempts to resolve this path, it ends up mangling it and errors out as the directory no longer exists (and my account does not have permission to write to the generated one).

The issue seems to occur with line 471 in classes/phpDoctor.php:

$absPath = str_replace('./', '', $absPath);

Which causes the folder to resolve to:

/usr/local/www/domain.com/subdomainhtdocs/mycode/

I have commented the line out and it is working for me just fine, but I'm not sure why it was there in the first place, so I do not know exactly what side-effects this would have, or what the line was trying to accomplish in the first place (to attempt to resolve the issue in a way that does not cause issues with some other type of path) - otherwise I'd just submit a patch.

Other than that everything seems to be working for me! :)

**Comment by tetsuo13** [comment]
Try my patch. Stripping out the slashdot is needed but only when it occurs at the beginning of the path. The line on 471 was first added in peej/phpdoctor@cb9847a759acb1523ff3c2a6e49e4b20e90884c5 and the code with my patch applied still passes the unit tests.

I'm not entirely sure why `realpath()` can't be used in the first place though:

``` php
$absPath = realpath($prefix . DIRECTORY_SEPARATOR . $path);
```

**Comment by NuclearDog** [comment]
Your patch seems to resolve the issue as well!

**Comment by tetsuo13** [comment]
Note that my patch is not in trunk, only in a fork. As a result closing this ticket beforehand doesn't help others who may be having the same issue.
