### ISSUE TITLE
PHP5: Assigning the return value of new by reference is deprecated

### ISSUE THREAD

**Issue by KampfCaspar** [peej/phpdoctor#6]
Is PHP4 compatibility still intended?

**Comment by peej** [comment]
I plan on supporting PHP4 until a time that it becomes impossible due to PHP4 syntax being dropped from PHP5/6.

What is your concern about the deprecated syntax? Do you think PHPDoctor should set the error level to turn of E_STRICT itself?

**Comment by KampfCaspar** [comment]
If PHP4 compatibility is your goal, then of course, the syntax is fine.

**Comment by blueyed** [comment]
You can fix this, and it won't break PHP4 compat: it will only create copies instead of references in PHP4.
