### ISSUE TITLE
PHPDoctor sees no difference between objects with the same name in different namespaces

### ISSUE THREAD

**Issue by binarte** [peej/phpdoctor#60]
Do the following code

```
namespace A {

    class Foo {}
    class Bar extends Foo{}

    class Bar_A extends Foo{}

}

namespace B {

    class Foo {}
    class Bar extends Foo{}

    class Bar_B extends Foo{}
}

namespace A\C{

    class Foo {}
    class Bar extends Foo{}

    class Bar_C extends Foo{}

}
```

And it will result in several errors - only a few will show up in the class trees, all versions of Foo will show as being parent of all versions of Bar and all versions of Bar will be shown as extending from A\Foo

**Comment by peej** [comment]
This appears to now be working correctly.
