### ISSUE TITLE
Add a composer.json

### ISSUE THREAD

**Issue by gossi** [peej/phpdoctor#67]
Composer is a php dependency management. Thus makes it easy to include one library into another project. phpdoctor is an ideal candidate to be included into many other projects as their documentation tool. Would be nice to do this via composer as this is becoming a very popular php dependency management. All that needs to be done is provide a composer.json file in the root of each project, submit it to their website and that's it, pretty easy. More can be found on https://github.com/composer/composer or their website: http://getcomposer.org/ as well as http://packagist.org/ the project repository.

Please contribute a composer.json to phpdoctor.

Thanks
gossi

**Comment by peej** [comment]
Took some time, but I've finally configured things with Composer and Packagist.
