### ISSUE TITLE
Use htmlStandardFormatter so that html files are created (Class 'Michelf\Markdown' not found)

### ISSUE THREAD

**Issue by zmorris** [peej/phpdoctor#74]
When you first download https://github.com/peej/phpdoctor/archive/master.zip, unzip it, change directory to it in the console and run:

php phpdoc.php phpdoctor.ini

You get:

PHP Fatal error:  Class 'Michelf\Markdown' not found in phpdoctor-master/formatters/markdownFormatter.php on line 24

It took me a while to figure out what was going on, but you have to go to line 51 of phpdoctor.ini and change it to:

formatter = htmlStandardFormatter
;formatter = markdownFormatter

So either the markdown formatter needs to be included in the zip file, or PHPDoctor needs to use html by default.

**Comment by peej** [comment]
Good call. I have updated this, thanks.
