### ISSUE TITLE
Does not escape HTML in code

### ISSUE THREAD

**Issue by nijel** [peej/phpdoctor#8]
When included code contains HTML (eg in global variable), it is not properly escaped.

For example following HTML is generated:

```
<code class="signature">public  mixed <strong>str_export1</strong> = '<select name="export_type"><option value="sqldumpfile">' . __('SQL dump (file download)'
```

**Comment by peej** [comment]
Great find. A fix for this will be in the repo soon.

**Comment by blueyed** [comment]
I have fixed this already in my fork, but not pushed yet (in case you want to wait and/or have not fixed it yourself already).
