### ISSUE TITLE
class constant handling

### ISSUE THREAD

**Issue by KampfCaspar** [peej/phpdoctor#9]
class constants are "documented" as final variables - which at least as of php 5.3 (static binding) is not correct...

class constants of type boolean get documented as "mixed" (always wrong for constants), while integer constants get "int" (correct).

Some constants - I didn't find a pattern yet - get documented with a preceding dollar sign; although NO instance with dollar sign is found in the sources.

**Comment by peej** [comment]
I've fixed the guessing of constant types from their contents. If you can figure out a use case for constants ending up with dollar signs, let me know.

If class constants shouldn't be documented as final, what should they be? I'm not familiar with 5.3 or static binding.

**Comment by KampfCaspar** [comment]
As there are certain semantic and syntactic differences to Java, I suggest:

a) extend the "chapters" fields, methods, constructors with a new "chapter" for constants. In there, constants should only ever have a simple "type".
b) remove "chapter" constructors - in PHP there can only ever be one constructor! - and include __construct/__destruct (with these names) on top of the methods list.

If you don't agree and don't want to make it parameterized, I suggest: constants should be "static final".

**Comment by peej** [comment]
I like this idea. It will take me a little while to get around to making this change.

**Comment by peej** [comment]
I have now made these changes.

Constructors are no longer "special" and are treated just as regular methods, they are always renamed to __construct if they are in the old PHP4 syntax.
Class constants are treated separate from other class variables and are labelled as static automatically. They are placed in their own section within the standard doclet.

Let me know if I got everything.
